server:
  port: 8888
  tomcat:
    connection-timeout: 2s
    keep-alive-timeout: 15s
    threads:
      max: 50
      min-spare: 5

spring:
  application:
    name: config-service
  cloud:
    config:
      server:
        git:
          uri: https://github.com/alanho123/config-repo.git
          default-label: main
          timeout: 5 # default 5
          clone-on-start: true # default false
          force-pull: true # default false

